src/ABC.Rotas.UI.Web/Controllers/MapaRotasController.cs
using ABC.Rotas.Application.Interfaces;
using ABC.Rotas.Application.ViewModels;
using ABC.Rotas.UI.Web.Mappers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ABC.Rotas.UI.Web.Controllers
{
    public class MapaRotasController : Controller
    {
        private readonly IRotaAppService AppRotaService;
        private readonly IPontoAppService AppPontoService;

        public MapaRotasController(IRotaAppService appRotaService, IPontoAppService appPontoService)
        {
            AppRotaService = appRotaService;
            AppPontoService = appPontoService;
        }

        public ActionResult Index()
        {
            InicializaDropdowns();
            return View();
        }

        //[HttpPost]
        //public JsonResult GetRotas(int pontoOrigem, int pontoDestino)
        //{
        //    var retorno = AppRotaService.BuscarRota(pontoOrigem, pontoDestino);
        //    return Json(retorno.Ligacoes, JsonRequestBehavior.AllowGet);
        //}

        private void InicializaDropdowns()
        {
            var pontos = Mapper.MapToSelectListItem(AppPontoService.PontosComLigacao().ToList());
            ViewBag.pontoOrigem = pontos;
            ViewBag.pontoDestino = pontos;
        }

    }
}

src/ABC.Rotas.UI.Web/Controllers/PontosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ABC.Rotas.Application.ViewModels;
using ABC.Rotas.Application.Interfaces;
using ABC.Rotas.UI.Web.Models;
using ABC.Rotas.Application.Servicos;
using ABC.Rotas.Application.AutoMapper;
using ABC.Rotas.UI.Web.Mappers;

namespace ABC.Rotas.UI.Web.Controllers
{
    public class PontosController : Controller
    {
        private readonly IPontoAppService AppPontoService;

        public PontosController(IPontoAppService appPontoService)
        {
            AppPontoService = appPontoService;
        }

        public ActionResult Index()
        {
            InicializaDropdowns();
            return View(new CadastroViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CadastroViewModel CadastroViewModel)
        {            
            if (ModelState.IsValid)
            {                
                CadastroViewModel.CreatePontoViewModel = AppPontoService.Adicionar(CadastroViewModel.CreatePontoViewModel);
                if (CadastroViewModel.CreatePontoViewModel.Erros.Count == 0)
                    return RedirectToAction("Index");
            }
            else
            {
                ModelState.Values.ToList().ForEach(x =>
                {
                    x.Errors.ToList().ForEach(e =>
                    {
                        CadastroViewModel.CreatePontoViewModel.Erros.Add(e.ErrorMessage);
                    });
                });                
            }

            InicializaDropdowns();

            return View("Index", CadastroViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CadastroViewModel CadastroViewModel)
        {            
            if (ModelState.IsValid)
            {                
                CadastroViewModel.EditPontoViewModel = AppPontoService.Atualizar(CadastroViewModel.EditPontoViewModel);
                if (CadastroViewModel.EditPontoViewModel.Erros.Count == 0)
                    return RedirectToAction("Index");
            }
            else
            {
                ModelState.Values.ToList().ForEach(x =>
                {
                    x.Errors.ToList().ForEach(e =>
                    {
                        CadastroViewModel.EditPontoViewModel.Erros.Add(e.ErrorMessage);
                    });
                
               });
            }

            InicializaDropdowns();

            return View("Index", CadastroViewModel);
        }


        [ValidateAntiForgeryToken]
        public ActionResult Delete(CadastroViewModel cadastroViewModel)
        {
            if (AppPontoService.Remover(cadastroViewModel.DeletePontoViewModelId) > 0)
                return RedirectToAction("Index");

            InicializaDropdowns();

            cadastroViewModel.Erros.Add("Nao foi possível excluir o ponto especificado");

            return View("Index", cadastroViewModel);
        }

        public JsonResult GetPontos()
        {
            return Json(AppPontoService.ObterTodos(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPontosComLigacao(int Id)
        {
            var lista = new List<PontoViewModel>();
            return Json(AppPontoService.PontosComLigacao(Id), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPontosSemLigacao(int Id)
        {
            var lista = new List<PontoViewModel>();
            return Json(AppPontoService.PontosSemLigacao(Id), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPontosCoordenadas(int Id)
        {
            var lista = new List<PontoViewModel>();
            return Json(AppPontoService.ObterPorId(Id), JsonRequestBehavior.AllowGet);
        }

        public void InicializaDropdowns()
        {
            var pontos = Mapper.MapToSelectListItem(AppPontoService.ObterTodos().ToList());
            ViewData["EditPontoViewModel.Id"] = pontos;
            ViewBag.CreateLigacaoViewModelP1Id = pontos;

            ViewBag.DeletePontoViewModelId = Mapper.MapToSelectListItem(AppPontoService.PontosSemLigacao().ToList());
            ViewBag.DeleteLigacaoViewModelP1Id = Mapper.MapToSelectListItem(AppPontoService.PontosComLigacao().ToList());

            pontos = Mapper.MapToSelectListItem(new List<PontoViewModel>());
            ViewBag.CreateLigacaoViewModelP2Id = pontos;
            ViewBag.DeleteLigacaoViewModelP2Id = pontos;
        }

    }
}

src/ABC.Rotas.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar">@Html.ActionLink("Home", "Index", "Home")</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cadastro", "Index", "Pontos")</li>
                    <li>@Html.ActionLink("Consulta Rotas", "Index", "MapaRotas")</li>
                </ul>
                @*<ul class="nav navbar-nav navbar-right">
                    @{
                        Html.RenderPartial("../Shared/_LoginPartial", new { id = "mapa" });
                    }

                </ul>*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/ABC.Rotas.UI.Web/Views/Shared/_Mapa.cshtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="~/Content/Coordenadas.css">
</head>

<body>
    <br />
    <canvas id="coordenadasCanvas" width="1200" height="1200" style="top:0;"></canvas>
</body>

</html>

<script src="~/Scripts/Mapa.js"></script>