src/ABC.Rotas.UI.Web/Controllers/LigacoesController.cs
using ABC.Rotas.Application.Interfaces;
using ABC.Rotas.Application.ViewModels;
using ABC.Rotas.UI.Web.Mappers;
using ABC.Rotas.UI.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ABC.Rotas.UI.Web.Controllers
{
    public class LigacoesController : Controller
    {
        private readonly ILigacaoAppService AppLigacaoService;
        private readonly IPontoAppService AppPontoService;
        
        public LigacoesController(ILigacaoAppService appLigacaoService, IPontoAppService appPontoService)
        {
            AppLigacaoService = appLigacaoService;
            AppPontoService = appPontoService;
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CadastroViewModel CadastroViewModel)
        {
            if (ModelState.IsValid)
            {
                LigacaoViewModel ligacaoViewModel = new LigacaoViewModel { 
                    P1_Id = CadastroViewModel.CreateLigacaoViewModelP1Id,
                    P2_Id = CadastroViewModel.CreateLigacaoViewModelP2Id,
                };                
                CadastroViewModel.CreateLigacaoViewModel = AppLigacaoService.Adicionar(ligacaoViewModel);
                if (CadastroViewModel.CreateLigacaoViewModel.Erros.Count == 0)
                    return RedirectToAction("Index");
            }
            else
            {
                ModelState.Values.ToList().ForEach(x =>
                {
                    x.Errors.ToList().ForEach(e =>
                    {
                        CadastroViewModel.CreateLigacaoViewModel.Erros.Add(e.ErrorMessage);
                    });
                });                
            }

            InicializaDropdowns();

            return View("../Pontos/Index", CadastroViewModel);
        }

        [ValidateAntiForgeryToken]
        public ActionResult Delete(CadastroViewModel cadastroViewModel)
        {
            if (ModelState.IsValid)
            {
                if (AppLigacaoService.Remover(cadastroViewModel.DeleteLigacaoViewModelP1Id, cadastroViewModel.DeleteLigacaoViewModelP2Id) > 0)
                    return RedirectToAction("Index", "Pontos");
            }

            InicializaDropdowns();

            cadastroViewModel.Erros.Add("Nao foi possível excluir a ligação especificada.");

            return View("../Pontos/Index", cadastroViewModel);
        }

        public JsonResult GetLigacoes()
        {
            List<LigacaoViewModel> retorno = new List<LigacaoViewModel>();
            AppLigacaoService.ObterTodos().ToList().ForEach(x =>
            {
                retorno.Add(new LigacaoViewModel
                {
                    Id = x.Id,
                    P1 = AppPontoService.ObterPorId(x.P1_Id),
                    P2 = AppPontoService.ObterPorId(x.P2_Id)
                });
            });

            return Json(retorno, JsonRequestBehavior.AllowGet);
        }

        public void InicializaDropdowns()
        {
            var pontos = Mapper.MapToSelectListItem(AppPontoService.ObterTodos().ToList());
            ViewData["EditPontoViewModel.Id"] = pontos;
            ViewBag.CreateLigacaoViewModelP1Id = pontos;

            ViewBag.DeletePontoViewModelId = Mapper.MapToSelectListItem(AppPontoService.PontosSemLigacao().ToList());
            ViewBag.DeleteLigacaoViewModelP1Id = Mapper.MapToSelectListItem(AppPontoService.PontosComLigacao().ToList());

            pontos = Mapper.MapToSelectListItem(new List<PontoViewModel>());
            ViewBag.CreateLigacaoViewModelP2Id = pontos;
            ViewBag.DeleteLigacaoViewModelP2Id = pontos;
        }

    }
}

src/ABC.Rotas.UI.Web/Controllers/PontosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ABC.Rotas.Application.ViewModels;
using ABC.Rotas.Application.Interfaces;
using ABC.Rotas.UI.Web.Models;
using ABC.Rotas.Application.Servicos;
using ABC.Rotas.Application.AutoMapper;
using ABC.Rotas.UI.Web.Mappers;

namespace ABC.Rotas.UI.Web.Controllers
{
    public class PontosController : Controller
    {
        private readonly IPontoAppService AppPontoService;

        public PontosController(IPontoAppService appPontoService)
        {
            AppPontoService = appPontoService;
        }

        public ActionResult Index()
        {
            InicializaDropdowns();
            return View(new CadastroViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CadastroViewModel CadastroViewModel)
        {            
            if (ModelState.IsValid)
            {                
                CadastroViewModel.CreatePontoViewModel = AppPontoService.Adicionar(CadastroViewModel.CreatePontoViewModel);
                if (CadastroViewModel.CreatePontoViewModel.Erros.Count == 0)
                    return RedirectToAction("Index");
            }
            else
            {
                ModelState.Values.ToList().ForEach(x =>
                {
                    x.Errors.ToList().ForEach(e =>
                    {
                        CadastroViewModel.CreatePontoViewModel.Erros.Add(e.ErrorMessage);
                    });
                });                
            }

            InicializaDropdowns();

            return View("Index", CadastroViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CadastroViewModel CadastroViewModel)
        {            
            if (ModelState.IsValid)
            {                
                CadastroViewModel.EditPontoViewModel = AppPontoService.Atualizar(CadastroViewModel.EditPontoViewModel);
                if (CadastroViewModel.EditPontoViewModel.Erros.Count == 0)
                    return RedirectToAction("Index");
            }
            else
            {
                ModelState.Values.ToList().ForEach(x =>
                {
                    x.Errors.ToList().ForEach(e =>
                    {
                        CadastroViewModel.EditPontoViewModel.Erros.Add(e.ErrorMessage);
                    });
                
               });
            }

            InicializaDropdowns();

            return View("Index", CadastroViewModel);
        }


        [ValidateAntiForgeryToken]
        public ActionResult Delete(CadastroViewModel cadastroViewModel)
        {
            if (AppPontoService.Remover(cadastroViewModel.DeletePontoViewModelId) > 0)
                return RedirectToAction("Index");

            InicializaDropdowns();

            cadastroViewModel.Erros.Add("Nao foi possível excluir o ponto especificado");

            return View("Index", cadastroViewModel);
        }

        public JsonResult GetPontos()
        {
            return Json(AppPontoService.ObterTodos(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPontosComLigacao(int Id)
        {
            var lista = new List<PontoViewModel>();
            return Json(AppPontoService.PontosComLigacao(Id), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPontosSemLigacao(int Id)
        {
            var lista = new List<PontoViewModel>();
            return Json(AppPontoService.PontosSemLigacao(Id), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPontosCoordenadas(int Id)
        {
            var lista = new List<PontoViewModel>();
            return Json(AppPontoService.ObterPorId(Id), JsonRequestBehavior.AllowGet);
        }

        public void InicializaDropdowns()
        {
            var pontos = Mapper.MapToSelectListItem(AppPontoService.ObterTodos().ToList());
            ViewData["EditPontoViewModel.Id"] = pontos;
            ViewBag.CreateLigacaoViewModelP1Id = pontos;

            ViewBag.DeletePontoViewModelId = Mapper.MapToSelectListItem(AppPontoService.PontosSemLigacao().ToList());
            ViewBag.DeleteLigacaoViewModelP1Id = Mapper.MapToSelectListItem(AppPontoService.PontosComLigacao().ToList());

            pontos = Mapper.MapToSelectListItem(new List<PontoViewModel>());
            ViewBag.CreateLigacaoViewModelP2Id = pontos;
            ViewBag.DeleteLigacaoViewModelP2Id = pontos;
        }

    }
}

src/ABC.Rotas.UI.Web/Views/Pontos/Index.cshtml
@model ABC.Rotas.UI.Web.Models.CadastroViewModel
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="~/Content/Coordenadas.css">
    <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/query.min.js" type="text/javascript"></script>-->    
    <script src="~/Scripts/jquery-3.4.1.js"></script>
</head>

<body>
    <h1 style="text-align:center">Controle de Rotas</h1>
    <br />
    <div class="container col-md-12">
        <div class="col-md-12">
            @using (Html.BeginForm("Create", "Pontos", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="col-md-4 form-group" style="border-radius:4px; border-style: groove;" align="center">
                    <p>
                        <h3>Incluir ponto</h3>
                    </p>
                    <p>&nbsp;</p><p>&nbsp;</p>
                    <p>
                        <span>Nome do ponto</span>
                        @Html.TextBoxFor(model => model.CreatePontoViewModel.Nome, new { @class = "form-control" })
                    </p>
                    <p>
                        <span>Coordenada X</span>
                        @Html.TextBoxFor(x => x.CreatePontoViewModel.X, new { @class = "form-control", @type="number", @max=59, @min="-59" })
                    </p>
                    <p>
                        <span>Coordenada Y</span>
                        @Html.TextBoxFor(x => x.CreatePontoViewModel.Y, new { @class = "form-control", @type="number", @max=59, @min="-59" })
                    </p>
                    <p><button type="submit" id="btnIncluirPonto" class="form-control btn btn-primary">Incluir ponto</button></p>
                </div>
            }
            @using (Html.BeginForm("Edit", "Pontos", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="col-md-4 form-group" style="border-radius:4px; border-style: groove" align="center">
                    <p>
                        <h3>Editar ponto</h3>
                    </p>
                    <p>
                        <span>&nbsp;</span>
                        @Html.DropDownListFor(x => x.EditPontoViewModel.Id, null, new { @class = "form-control", @id = "EditPontoViewModelId" })
                    </p>
                    <p>
                        <span>Nome do ponto</span>
                        @Html.TextBoxFor(model => model.EditPontoViewModel.Nome, new { @class = "form-control", @id = "EditPontoViewModelNome" })
                    </p>
                    <p>
                        <span>Coordenada X</span>
                        @Html.TextBoxFor(x => x.EditPontoViewModel.X, new { @class = "form-control", @type = "number", @max = 59, @min = "-59", @id = "EditPontoViewModelX" })
                    </p>
                    <p>
                        <span>Coordenada Y</span>
                        @Html.TextBoxFor(x => x.EditPontoViewModel.Y, new { @class = "form-control", @type = "number", @max = 59, @min = "-59", @id = "EditPontoViewModelY" })
                    </p>
                    <p><button id="btnAlterarPonto" class="form-control btn btn-primary">Editar ponto</button></p>
                </div>
            }
            @using (Html.BeginForm("Delete", "Pontos", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="col-md-4 form-group" style="border-radius:4px; border-style: groove" align="center">
                    <p>
                        <h3>Excluir ponto</h3>
                    </p>
                    <p>&nbsp;</p><p>&nbsp;</p>
                    <p>
                        <span>Nome do ponto</span>
                        @Html.DropDownListFor(x => x.DeletePontoViewModelId, null, new { @class = "form-control" } )
                    </p>
                    <p>
                        <span>Coordenada X</span>
                        <input type="text" id="coordenadaX" class="form-control" readonly="readonly" />
                    </p>
                    <p>
                        <span>Coordenada Y</span>
                        <input type="text" id="coordenadaY" class="form-control" readonly="readonly" />
                    </p>
                    <p><button id="btnExcluirPonto" class="form-control btn btn-primary">Excluir ponto</button></p>
                </div>
            }
        </div><br/>
    </div>
    <div class="col-md-12" style="align-self:center">
        @foreach (var item in Model.CreatePontoViewModel.Erros)
        {
            <p style="text-align: center; font-size: x-large; color: red" class="col-md-12">
                @Html.Raw(item)
            </p>
        }
        @foreach (var item in Model.EditPontoViewModel.Erros)
        {
            <p style="text-align: center; font-size: x-large; color: red" class="col-md-12">
                @Html.Raw(item)
            </p>
        }

        @foreach (var item in Model.CreateLigacaoViewModel.Erros)
        {
            <p style="text-align: center; font-size:x-large; color: red" class="col-md-12">
                @Html.Raw(item)
            </p>
        }
        @foreach (var item in Model.DeleteLigacaoViewModel.Erros)
        {
            <p style="text-align: center; font-size:x-large; color: red" class="col-md-12">
                @Html.Raw(item)
            </p>
        }

        @foreach (var item in Model.Erros)
        {
            <p style="text-align: center; font-size:x-large; color: red" class="col-md-12">
                @Html.Raw(item)
            </p>
        }

    </div>

    <div class="container col-md-12">
        @using (Html.BeginForm("Create", "Ligacoes", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="col-md-6 form-group" style="border-radius:4px; border-style: groove" align="center">
                <p>
                    <h3>Incluir ligaçao</h3>
                </p>
                <p>
                    <span>Primeiro ponto</span>
                    @Html.DropDownListFor(x => x.CreateLigacaoViewModelP1Id, null, new { @class = "form-control" })
                </p>
                <p>
                    <span>Segundo ponto</span>
                    @Html.DropDownListFor(x => x.CreateLigacaoViewModelP2Id, null, new { @class = "form-control" })
                </p>
                <p><button id="btnIncluirLigacao" class="form-control btn btn-primary">Incluir ligação</button></p>
            </div>
        }
        @using (Html.BeginForm("Delete", "Ligacoes", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="col-md-6 form-group" style="border-radius:4px; border-style: groove" align="center">
                <p>
                    <h3>Excluir ligação</h3>
                </p>
                <p>
                    <span>Primeiro ponto</span>
                    @Html.DropDownListFor(x => x.DeleteLigacaoViewModelP1Id, null, new { @class = "form-control" })
                </p>
                <p>
                    <span>Segundo ponto</span>
                    @Html.DropDownListFor(x => x.DeleteLigacaoViewModelP2Id, null, new { @class = "form-control" })
                </p>
                <p><button id="btnExcluirLigacao" class="form-control btn btn-primary">Excluir ligação</button></p>
            </div>
        }
    </div>
    <div>
        @{
            Html.RenderPartial("../Shared/_Mapa", new { id = "mapa" });
        }

    </div>
</body>

</html>

<script src="~/Scripts/Cadastro.js"></script>